### ISSUE TITLE
Doxygen v1.9.6

### ISSUE THREAD

**Issue by tim-gromeyer** [mattnotmitt/doxygen-action#33]
Doxygen v1.9.6 got released lately. Would be cool to use it in my documentation.

**Comment by mattnotmitt** [comment]
Doxygen 1.9.6 is currently available on the `edge` tag. I can't pin the versions in alpine `edge` due to [the issues ](https://github.com/mattnotmitt/doxygen-action/issues/29) when I did so with `1.9.3`. I'll release a `1.9.6` tag when Alpine releases a new stable version (probably around March?) :)

**Comment by tim-gromeyer** [comment]
I'll test it out soon. Thanks in advance

**Comment by tim-gromeyer** [comment]
It works, thanks!

**Comment by HiranChaudhuri** [comment]
Meanwhile Doxygen 1.9.8 is released. A repetition? Should I open a new issue?

Maybe a solution would be that the Doxygen version would be installed directly rather than through the Alpine packages to reduce latency. This might even be based on a parameter that is user-configurable.

**Comment by steve02081504** [comment]
@mattnotmitt
https://github.com/doxygen/doxygen/releases/tag/Release_1_10_0 !
thx for hard work!

**Comment by mattnotmitt** [comment]
Sorry for the embarrassingly long delay - published Doxygen `1.9.6` and `1.9.8` and `1.10.0` is available on the `edge` tag
